src/discord/discord.service.ts
To reduce the workaround in importing classes like "NotFoundException" or "UnauthorizedException", added the base HttpException and HttpStatus class.
=> discordService: HttpException class convention for error responses

.github/workflows/labels.yml
=> Added Labels

src/discord/discord.service.ts
Added small logic for updating existing user in `discord`-Array
=> Fix Issue 46 - Update User

README.md
Just to make read me attractive
! a small effort 
Fixes #52
=> Added the  line made with love by eddiehubbers 

package-lock.json, src/app.module.ts, src/standup/dto/CreateStandup.dto.ts, src/standup/dto/SearchStandup.dto.ts, src/standup/interfaces/Standup.interface.ts, src/standup/standup.controller.spec.ts, src/standup/standup.controller.ts, src/standup/standup.module.ts, src/standup/standup.service.spec.ts, src/standup/standup.service.ts, test/features/standup.feature, test/step-definitions/responses.ts
=> Fix Issue #11 - Standup Module

package-lock.json, package.json, src/app.module.ts, src/discord/dto/create-discord.dto.ts, src/github/communitystats-mapping.service.spec.ts, src/github/communitystats-mapping.service.ts, src/github/dto/github.dto.ts, src/github/github.controller.spec.ts, src/github/github.controller.ts, src/github/github.module.ts, src/github/github.service.spec.ts, src/github/github.service.ts, src/github/interfaces/github.interface.ts, src/main.ts, test/features/github.feature
closes #44 
Module which collects Github Data which are sent from an Action.
=> Issue 44 - Github Data Collection

src/github/geocoding.service.spec.ts, src/github/geocoding.service.ts, src/github/github.controller.spec.ts, src/github/github.module.ts, src/github/github.service.spec.ts, src/github/github.service.ts, test/features/github.feature
closes #66 
Geocode location from githubprofile to coordinates for display on a map
=> Issue-66 Geocodingservice

src/discord/discord.controller.ts, src/discord/discord.service.ts, src/discord/dto/discord.dto.ts, src/discord/dto/read-discord.dto.ts, src/discord/dto/update-discord.dto.ts, src/discord/interfaces/discord.interface.ts, src/standup/dto/standup.dto.ts, src/standup/standup.controller.ts, src/standup/standup.service.ts
fixes #71 
fixes #41 
Consistent naming of DTOs
Adds Validation to DTOs
=> docs: Swagger Declaration Consistent

package-lock.json, package.json, src/app.module.ts, src/calendar/calendar.controller.spec.ts, src/calendar/calendar.controller.ts, src/calendar/calendar.module.ts, src/calendar/calendar.service.spec.ts, src/calendar/calendar.service.ts, src/calendar/dto/calendar.dto.ts, src/calendar/interfaces/calendar.interface.ts, src/discord/discord.service.ts, src/github/github.service.ts, src/main.ts, src/standup/standup.service.ts, test/features/calendar.feature, test/features/discord.feature, test/features/github.feature, test/features/standup.feature, test/step-definitions/requests.ts, test/step-definitions/responses.ts
fixes #58 
fixes #75 
Calendar Module for saving community Events
=> issue-58--Calendar-Module

test/features/calendar.feature, test/features/discord.feature, test/features/github.feature, test/features/standup.feature, test/step-definitions/responses.ts, test/support/world.ts
closes #78
Example
```diff
- And the response should contains:
-             | statusCode | 400                                                                                                                                                                                                                                                                                                                                              - |
-             | message    | ["name must be a string","name should not be empty","platform must be one of the following values: - YouTube, Twitch","platform must be a string","platform should not be empty","author should not be empty","startDate should - not be empty","startDate must be a Date instance","endDate must be a Date instance","endDate should not be …
```
=> Refactored step defs for automated testing

package-lock.json, package.json
=> chore: Bump dependency version (#92)

.github/workflows/build.yml
Using the package script command to be consistent
=> fix: use script command

README.md, docker-compose.yml
closes #89 
- running Stargate locally with docker
-
=> feat: docker compose (#89)

src/github/github.controller.spec.ts, src/github/github.controller.ts, src/github/github.module.ts, src/github/github.service.spec.ts, src/github/github.service.ts, src/github/interfaces/github.interface.ts, test/features/github.feature
=> feat: init github to database

src/discord/discord.controller.spec.ts, src/discord/discord.controller.ts, src/discord/discord.module.ts, src/discord/discord.service.spec.ts, src/discord/discord.service.ts, src/discord/interfaces/discord.interface.ts, test/features/discord.feature, test/features/github.feature
=> feat: discord-module to database

src/calendar/calendar.controller.spec.ts, src/calendar/calendar.controller.ts, src/calendar/calendar.module.ts, src/calendar/calendar.service.spec.ts, src/calendar/calendar.service.ts, src/calendar/interfaces/calendar.interface.ts, test/features/calendar.feature, test/step-definitions/responses.ts
=> feat: calendar-module to database

package.json
added description and author to package
=> Updated file package.json

.github/workflows/docker.yml, Dockerfile, README.md, package-lock.json, package.json
closes #114 
Another solution to #110
=> fix: husky check (#114)

.husky/pre-commit
=> fix: husky not to run tests (#121)

src/calendar/calendar.service.ts, src/discord/discord.service.ts, src/github/github.service.ts, src/standup/standup.service.ts
=> fix: no data, empty result (#134)

package-lock.json, package.json, test/step-definitions/requests.ts
=> test: delete keyspace before tests

test/step-definitions/requests.ts
=> test: fix timeout of deleting keyspace (#151)

test/features/hello-world.feature, test/step-definitions/responses.ts, test/support/regexes.ts
=> test: add e2e-test

docker-compose.yml
=> chore: upgrade stargate for M1 (#169)

.github/workflows/docs.yml
Docs will run on all changes in `main`
=> fix: run docs for all changes (#161)

docs/authentication.adoc, docs/index.adoc, docs/readme.adoc
=> docs: initialize docs for authentication

src/auth/auth.controller.ts, test/features/auth.feature
=> fix: return 200 instead of 400

CODE_OF_CONDUCT.md
Hello @krishguptadev ,
This PR is regarding the issue number #241 .
Please let me know if any changes are required.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/242"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updating version and email in COC #241

src/github/github-profile.service.ts, src/github/github.controller.ts
closese #257
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/258"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Migrate to Controller

package-lock.json, src/github/data/event-map.ts, src/github/github-profile.service.ts, src/github/github.controller.ts, test/features/github.feature
The Events aren't mapped at every occurence. This PR fixes it
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/272"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: mapping for all events

package-lock.json, src/github/github-profile.service.ts
closes #283
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/284"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: location update

package-lock.json, src/github/github.controller.ts
closes #295
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/296"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: populate websocket object

package-lock.json, src/github/github-event.service.ts, src/github/github.controller.ts
closes #295
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/297"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: populated object

package-lock.json, src/github/github.controller.ts
closes #295
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/298"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: webhook properties

README.md
Closes #291 
-removed the link that was not working in readme file, in the description section.
- [ x] I have updated the documentation accordingly.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/294"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> removed the link not working in readme. Closes #291

.dockerignore
closes #305 
- Added more elements to `.dockerignore` to reduce the build size 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/306"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: improved the `.dockerignore`

README.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/api/pull/307"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fixed a typo in line no 91(undefined).

README.md
=> Grammar, Typos & Organized socials
